# Deployment for Food Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-app
  template:
    metadata:
      labels:
        app: food-app
    spec:
      containers:
      - name: food-container
        image: chand93/food-service:latest
        ports:
        - containerPort: 5000

---
# Service for Food Service
apiVersion: v1
kind: Service
metadata:
  name: food-service
spec:
  selector:
    app: food-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000

---
# Deployment for Clothing Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clothing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clothing-app
  template:
    metadata:
      labels:
        app: clothing-app
    spec:
      containers:
      - name: clothing-container
        image: chand93/clothing-service:latest
        ports:
        - containerPort: 5000

---
# Service for Clothing Service
apiVersion: v1
kind: Service
metadata:
  name: clothing-service
spec:
  selector:
    app: clothing-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000

---
# Ingress Configuration
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: ""
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /food(/|$)(.*)
        backend:
          service:
            name: food-service
            port:
              number: 80
      - pathType: ImplementationSpecific
        path: /clothing(/|$)(.*)
        backend:
          service:
            name: clothing-service
            port:
              number: 80

