pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials-id')
    }

    stages {
        stage('Build Food Microservice Image') {
            steps {
                script {
                    docker.build("docker.io/chand93/food-service:${env.BUILD_NUMBER}", "./food").withRun { c ->
                        // Tagging the image with 'latest'
                        docker.image("docker.io/chand93/food-service:${env.BUILD_NUMBER}").tag("latest")
                    }
                }
            }
        }

        stage('Push Food Microservice Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials-id') {
                        docker.image("docker.io/chand93/food-service:${env.BUILD_NUMBER}").push()
                        docker.image("docker.io/chand93/food-service:latest").push()
                    }
                }
            }
        }
    }

    post {
        success {
            echo "Successfully built and pushed Food Microservice image"
        }
        failure {
            echo "Failed to build or push Food Microservice image"
        }
    }
}
